apiVersion: v1
kind: Service
metadata:
  name: backendfeed-app
  labels:
    run: backendfeed-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: backendfeed-app