apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-app
  labels:
    app: reverseproxy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy-app
  template:
    metadata:
      labels:
        app: reverseproxy-app
    spec:
      containers:
      - name: reverseproxy
        image: ayomideajewole/reverseproxy:v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
      restartPolicy: Always