apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-app
  labels:
    run: reverseproxy-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    run: reverseproxy-app